DELETE http://localhost:3003/api/blogs/61eaec50ac375a2b1035e253 HTTP/1.1
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvdWxhIiwiaWQiOiI2MWVjNDgzYjM0Mzg2MTA1ZjRmNThlNzYiLCJpYXQiOjE2NDI4Nzc0MDMsImV4cCI6MTY0Mjg4MTAwM30.b4H-uyoIrDONGqfB0AGpXQxrDr7Kjz7C3KXLnDI7-Oc